// productos.js
const PRODUCTS = [

  // =========================================================================
  // Versión Fan / MANGA CORTA
  // =========================================================================

  // --- BARCELONA (Fan - Manga Corta) ---
  {
    id: "FCB-FMC-01",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 24-25.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 24-25 2.jpg"
  },
  {
    id: "FCB-FMC-02",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 25-26 2.jpg"
  },
  {
    id: "FCB-FMC-03",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2026/27",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 26-27.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Local 26-27 2.jpg"
  },
  {
    id: "FCB-FMC-04",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Visita 24-25.png",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Visita 24-25 2.jpg"
  },
  {
    id: "FCB-FMC-05",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Visita 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Visita 25-26 2.jpg"
  },
  {
    id: "FCB-FMC-06",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Tercera 24-25.png",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Tercera 24-25 2.jpg"
  },
  {
    id: "FCB-FMC-07",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Tercera 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Tercera 25-26 2.jpg"
  },
  {
    id: "FCB-FMC-08",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Edición especial",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Cuarta 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Barcelona/Barcelona Cuarta 25-26 2.jpg"
  },

  // --- REAL MADRID (Fan - Manga Corta) ---
  {
    id: "RM-FMC-01",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 23-24.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 23-24 2.jpeg"
  },
  {
    id: "RM-FMC-02",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 24-25.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 24-25 2.jpeg"
  },
  {
    id: "RM-FMC-03",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 25-26 2.jpg"
  },
  {
    id: "RM-FMC-04",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Fan",
    temporada: "2026/27",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 26-27.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Local 26-27 2.jpg"
  },
  {
    id: "RM-FMC-05",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 23-24.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 23-24 2.jpeg"
  },
  {
    id: "RM-FMC-06",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 24-25.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 24-25 2.jpeg"
  },
  {
    id: "RM-FMC-07",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 25-26 2.jpg"
  },
  {
    id: "RM-FMC-08",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 23-24.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 23-24 2.jpeg"
  },
  {
    id: "RM-FMC-09",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 13000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 24-25.jpeg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 24-25 2.jpeg"
  },
  {
    id: "RM-FMC-10",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 25-26 2.jpg"
  },
  {
    id: "RM-FMC-11",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2026/27",
    disponible: true,
    price: 13000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 26-27.jpg",
    imagenTrasera: "Version Fan/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 26-27 2.jpg"
  },

  // =========================================================================
  // Versión Fan / MANGA LARGA
  // =========================================================================

  // --- BARCELONA (Fan - Manga Larga) ---
  {
    id: "FCB-FML-01",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 20000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Local ML 24-25.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Local ML 24-25 2.jpg"
  },
  {
    id: "FCB-FML-02",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Local ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Local ML 25-26 2.jpg"
  },
  {
    id: "FCB-FML-03",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Fan",
    temporada: "2024/25",
    disponible: true,
    price: 20000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 24-25.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 24-25 2.jpg"
  },
  {
    id: "FCB-FML-04",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 25-26 2.jpg"
  },
  {
    id: "FCB-FML-05",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 25-26 2.jpg"
  },

  // --- REAL MADRID (Fan - Manga Larga) ---
  {
    id: "RM-FML-01",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 20000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 23-24.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 23-24 2.jpg"
  },
  {
    id: "RM-FML-02",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 25-26 2.jpg"
  },
  {
    id: "RM-FML-03",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Fan",
    temporada: "2026/27",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 26-27.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 26-27 2.jpg"
  },
  {
    id: "RM-FML-04",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 20000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 23-24.jpeg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 23-24 2.jpeg"
  },
  {
    id: "RM-FML-05",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 25-26 2.jpg"
  },
  {
    id: "RM-FML-06",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2023/24",
    disponible: true,
    price: 20000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 23-24.jpeg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 23-24 2.jpeg"
  },
  {
    id: "RM-FML-07",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Fan",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Fan",
    temporada: "2025/26",
    disponible: true,
    price: 20000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 25-26.jpg",
    imagenTrasera: "Version Fan/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 25-26 2.jpg"
  },

  // =========================================================================
  // Versión Jugador / MANGA CORTA
  // =========================================================================

  // --- BARCELONA (Jugador - Manga Corta) ---
  {
    id: "FCB-JMC-01",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 24-25 2.jpeg"
  },
  {
    id: "FCB-JMC-02",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 25-26 2.jpg"
  },
  {
    id: "FCB-JMC-03",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2026/27",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 26-27.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Local 26-27 2.jpeg"
  },
  {
    id: "FCB-JMC-04",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Visita 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Visita 24-25 2.jpeg"
  },
  {
    id: "FCB-JMC-05",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Visita 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Visita 25-26 2.jpg"
  },
  {
    id: "FCB-JMC-06",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Tercera 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Tercera 24-25 2.jpeg"
  },
  {
    id: "FCB-JMC-07",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Tercera 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Tercera 25-26 2.jpg"
  },
  {
    id: "FCB-JMC-08",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Edición especial",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Cuarta 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Barcelona/Barcelona Cuarta 25-26 2.jpg"
  },

  // --- REAL MADRID (Jugador - Manga Corta) ---
  {
    id: "RM-JMC-01",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2023/24",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 23-24.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 23-24 2.jpg"
  },
  {
    id: "RM-JMC-02",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 24-25 2.jpeg"
  },
  {
    id: "RM-JMC-03",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Local",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Local 25-26 2.jpg"
  },
  {
    id: "RM-JMC-05",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2023/24",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 23-24.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 23-24 2.jpg"
  },
  {
    id: "RM-JMC-06",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 24-25 2.jpeg"
  },
  {
    id: "RM-JMC-07",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Visita 25-26 2.jpg"
  },
  {
    id: "RM-JMC-08",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2023/24",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 23-24.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 23-24 2.jpg"
  },
  {
    id: "RM-JMC-09",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 18000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 24-25.jpeg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 24-25 2.jpeg"
  },
  {
    id: "RM-JMC-10",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Tercera 25-26 2.jpg"
  },
  {
    id: "RM-JMC-12",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Corta",
    modelo: "Edición especial",
    version: "Jugador",
    temporada: "2026/27",
    disponible: true,
    price: 18000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Edicion Especial 26-27.jpg",
    imagenTrasera: "Version Jugador/Manga Corta/La Liga/Real Madrid/Real Madrid Edicion Especial 26-27 2.jpg"
  },

  // =========================================================================
  // Versión Jugador / MANGA LARGA
  // =========================================================================

  // --- BARCELONA (Jugador - Manga Larga) ---
  {
    id: "FCB-JML-01",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Local ML 24-25.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Local ML 24-25 2.jpg"
  },
  {
    id: "FCB-JML-02",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Local ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Local ML 25-26 2.jpg"
  },
  {
    id: "FCB-JML-03",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Visita ML 25-26 2.jpg"
  },
  {
    id: "FCB-JML-04",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 24-25.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 24-25 2.jpg"
  },
  {
    id: "FCB-JML-05",
    equipo: "Barcelona",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Barcelona/Barcelona Tercera ML 25-26 2.jpg"
  },

  // --- REAL MADRID (Jugador - Manga Larga) ---
  {
    id: "RM-JML-01",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2023/24",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 23-24.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 23-24 2.jpg"
  },
  {
    id: "RM-JML-02",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 24-25.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 24-25 2.jpg"
  },
  {
    id: "RM-JML-03",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 25-26 2.jpg"
  },
  {
    id: "RM-JML-04",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Local",
    version: "Jugador",
    temporada: "2026/27",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL", "2XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 26-27.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Local ML 26-27 2.jpg"
  },
  {
    id: "RM-JML-05",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 24-25.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 24-25 2.jpg"
  },
  {
    id: "RM-JML-06",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Visita",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Visita ML 25-26 2.jpg"
  },
  {
    id: "RM-JML-07",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2024/25",
    disponible: true,
    price: 24000,
    nuevo: false,
    popular: false,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 24-25.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 24-25 2.jpg"
  },
  {
    id: "RM-JML-08",
    equipo: "Real Madrid",
    liga: "La Liga",
    tipo: "Versión Jugador",
    manga: "Manga Larga",
    modelo: "Tercera",
    version: "Jugador",
    temporada: "2025/26",
    disponible: true,
    price: 24000,
    nuevo: true,
    popular: true,
    tallas: ["S", "M", "L", "XL"],
    imagen: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 25-26.jpg",
    imagenTrasera: "Version Jugador/Manga Larga/La Liga/Real Madrid/Real Madrid Tercera ML 25-26 2.jpg"
  }

];
